# https://github.com/marketplace/actions/release-changelog-builder
name: 'CI'
on:
  repository_dispatch:
    types: [create-release]

concurrency:
  group: ${{ github.event.pull_request.number }}-ci
  cancel-in-progress: true

jobs:  
  release:
    if: github.event.client_payload.auto_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Release tag
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/naturalett/maven-hello-world/releases/latest | jq -r '.tag_name' > latest_release_tag.txt
      - name: Checkout latest release tag
        id: release_tag
        run: |
          toTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "toTag=$toTag" >> "$GITHUB_ENV"
          git checkout $toTag
      - name: "Echo github event"
        id: github_event
        run: |
          echo "${{ github.event.client_payload.auto_release }}"
      - name: "Get Previous Tag"
        id: git_tag
        run: |
          git fetch -a
          echo "fromTag=$(cat latest_release_tag.txt)" >> "$GITHUB_ENV"
      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/configs/configuration_repo.json"
          fromTag: ${{env.fromTag}}
          toTag: ${{env.toTag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          tag_name: ${{env.toTag}}
      - name: short commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: list artifact
        id: list_artifact
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/naturalett/maven-hello-world/actions/artifacts
      - name: short commit
        id: vars_2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "archive_download_url=$(curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/naturalett/maven-hello-world/actions/artifacts | jq -r '.artifacts[0].archive_download_url')" >> "$GITHUB_ENV"
      - name: Download math result for job 2
        id: math_vars
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ env.archive_download_url }} -o maven-hello-world-${{ env.sha_short }}.jar
          ls -al .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/*.*.jar
          tag: ${{env.toTag}}