# https://github.com/marketplace/actions/release-changelog-builder
name: 'CI'
on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed
  repository_dispatch:
    types: [my-event]

concurrency:
  group: ${{ github.event.pull_request.number }}-ci
  cancel-in-progress: true

jobs:          
  release:
    if: ${{ github.event.client_payload.auto_release }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        if: ${{ github.event.client_payload.auto_release }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Echo github event"
        if: ${{ github.event.client_payload.auto_release }}
        id: github_event
        run: |
          echo "${{ github.event.client_payload.auto_release }}"
      - name: "Get Previous Tag"
        if: ${{ github.event.client_payload.auto_release }}
        id: git_tag
        run: |
          git fetch -a
          echo "fromTag=$(git describe --abbrev=0 --tags $(git log -2 --format='%H' | head -2 | sed '1d'))" >> "$GITHUB_ENV"
      - name: "Build Changelog"
        if: ${{ github.event.client_payload.auto_release }}
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: ".github/configs/configuration_repo.json"
          fromTag: ${{env.fromTag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Release"
        if: ${{ github.event.client_payload.auto_release }}
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}