# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: ""
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: 20.0.1
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Configure Git User
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Configure GPG Key
      run: |
        echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    - name: Release with Maven
      run: |
        java --version
        mvn --version
        mvn -X -B -U \
          clean \
          release:prepare \
          release:perform \
          javadoc:jar \
          source:jar \
          deploy \
          -Pci-cd \
          -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
          -Dusername=naturalett \
          -s settings.xml \
          -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
          -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
          -Dpassword=${{ secrets.TOKEN }}
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    # - name: build artifact
    #   run: mvn clean package
    # - name: Release with Maven
    #   run: |
    #     mvn -X --batch-mode \
    #       release:clean \
    #       release:prepare \
    #       release:perform \
    #       -Dusername=naturalett \
    #       -s settings.xml \
    #       -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
    #       -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
    #   env:
    #     OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #     OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
    #     MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    #     MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    # - name: Deploy with Maven
    #   run: |
    #     mvn -U -X clean javadoc:jar source:jar -Pci-cd deploy
    #   env:
    #     MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #     MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    #     MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    #     MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    # - name: Publish to Central Repository
    #   run: |
    #     mvn \
    #       --no-transfer-progress \
    #       --batch-mode \
    #       clean deploy
    #   env:
    #     MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #     MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    #     MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}